name: Arch Linux CI
on:
  workflow_dispatch:
  push:
    paths:
      - 'pkg'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:stable
    steps:
      - name: Install dependencies
        run: |
          apt update -y
          apt install -y equivs

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run build/test commands
        run: |
          equivs-build pkg
          PKGN=$(awk '/^Package:/ {print $2}' pkg)
          echo "PKG=${PKGN}" >> $GITHUB_ENV
          FILE1=$(realpath $PKGN-_99.9.9_all.deb)
          echo "FILE1=${FILE1}" >> $GITHUB_ENV
          

      - name: Create GitHub Release and Upload ZIP
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.PKG }}
          files: |
            ${{ env.FILE1 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
